spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tracktv
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

security:
  key: 'secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret'

